const products =[ 
{name:"Tecno camon 11", price:340 , image:"/images/pic (1).jpg"},
{name:"Tecno camon 12", price:370 , image:"/images/pic (2).jpg"},
{name:"Tecno camon 13", price:440 , image:"/images/pic (3).jpg"},
{name:"Tecno camon 14", price:465 , image:"/images/pic (4).jpg"},
{name:"Tecno camon 15", price:490 , image:"/images/pic (5).jpg"},
{name:"Tecno camon 16", price:1080 , image:"/images/pic (6).jpg"},
{name:"Tecno camon 17", price:340 , image:"/images/pic (7).jpg"},
{name:"Tecno spark 5", price:340 , image:"/images/pic (8).jpg"},
{name:"Tecno spark 7", price:340 , image:"/images/pic (9).jpg"},
{name:"Infinix Note 2", price:340 , image:"/images/pic (10).jpg"},
{name:"Infinix Note 4", price:340 , image:"/images/pic (11).jpg"},
{name:"Infinix Hot S", price:340 , image:"/images/pic (12).jpg"},
{name:"Itel Pop 3", price:340 , image:"/images/pic (13).jpg"},
{name:"Itel s45", price:340 , image:"/images/pic (14).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (15).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (16).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (17).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (18).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (19).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (20).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (21).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (22).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (23).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (24).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (25).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (26).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (27).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (28).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (29).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (30).jpg"},
{name:"Tecno camon 11", price:340 , image:"/images/pic (31).jpg"}
];

export default products;